name: Bug report
description: Create a report to help us improve
title: "[bug] "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: "1. ..."
  - type: input
    id: version
    attributes:
      label: Python version
